import Head from "next/head";
import Image from "next/image";
import { createRef, RefObject, useEffect, useState } from "react";
// import Delivery from "static/delivery.png";

// import Sea from "static/sea.svg";
// import socialShare from "static/social_share.svg";
// import shops from "static/shops.svg";
// import connected from "static/connected.svg";
// import deliveryBike from "static/delivery-bike.svg";
// import house from "static/house.svg";
// import clock from "static/clock.svg";
// import Shop from "static/shop.svg";
import Fish from "../img/fish.svg";
export default function Home() {
  const [path, setPath] = useState("");
  const [svgHeight, setSvgHeight] = useState(0);
  const [currect, setCurrect] = useState(0);
  const [maxHeight, setMaxHeight] = useState(0);

  const mainBlock = createRef<HTMLDivElement>();
  const createPath = (
    ciricle: NodeListOf<HTMLElement>,
    section: NodeListOf<HTMLElement>
  ): string => {
    let createPath: string = "";
    ciricle.forEach((item: HTMLElement, index: number) => {
      if (index != ciricle.length - 1) {
        createPath += `M${Math.trunc(
          item.offsetLeft + item.offsetWidth / 2
        )} ${Math.trunc(item.offsetTop + item.offsetHeight / 2)}Q ${Math.trunc(
          item.offsetLeft + item.offsetWidth / 2
        )} ${
          section[index].offsetTop + section[index].offsetHeight
        } ${Math.trunc(section[index].offsetWidth / 2)} ${Math.trunc(
          section[index].offsetTop + section[index].offsetHeight
        )}T${Math.trunc(
          ciricle[index + 1].offsetLeft + ciricle[index + 1].offsetWidth / 2
        )} ${Math.trunc(
          ciricle[index + 1].offsetTop + ciricle[index + 1].offsetHeight / 2
        )}`;
      }
    });
    return createPath;
  };
  useEffect(() => {
    const node = mainBlock.current;
    if (node) {
      const ciricle: NodeListOf<HTMLElement> =
        node.querySelectorAll(".ciricle");
      const section: NodeListOf<HTMLElement> =
        node.querySelectorAll(".path-sec");

      window.addEventListener("scroll", () => {
        setCurrect(window.scrollY - section[0].offsetTop);
        setMaxHeight(
          section[section.length - 1].offsetTop - section[0].offsetTop
        );
      });

      setSvgHeight(
        section[section.length - 1].offsetTop +
          section[section.length - 1].offsetHeight
      );
      window.addEventListener("resize", () => {
        setPath(createPath(ciricle, section));
      });
      setPath(createPath(ciricle, section));
    }
  }, []);

  return (
    <div className="container" ref={mainBlock}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>{`
        .mover {
          offset-distance: ${(currect / maxHeight) * 100}%;
          offset-path: path("${path}");
        }
      `}</style>
      <img
        className="mover"
        src="static/delivery.png"
      />
      {/* <Image className="mover"  src={Delivery} alt="Picture of the author" width='256' height='256' layout='fixed' /> */}

      <svg
        style={{
          zIndex: -1,
          width: "100vw",
          height: `${svgHeight}px`,
          position: "absolute",
          left: 0,
          top: 0,
        }}
      >
        <path
          d={path}
          stroke="#387298"
          fill="transparent"
          strokeLinecap="round"
          style={{
            fillRule: "evenodd",
            strokeWidth: 3,
            strokeLinecap: "butt",
            strokeLinejoin: "miter",
            strokeMiterlimit: 4,
            strokeDasharray: 10,
            strokeDashoffset: 0,
          }}
        ></path>
      </svg>

      {/* <img src="static/delivery.png" className="mover" alt=""  */}
      {/* style={{
      offsetDistance: (currect / maxHeight) * 100 + "%",
      offsetPath: `path("${path2}")`
    }}/> */}

      <section className="welcome">
        <div className="welcome__content">
          <h1 className="welcome__title">FEOFISH</h1>
          <Image
            className="about__img"
            src={Fish}
            alt="Shop"
            width="256"
            height="256"
          />

        </div>
        <div className="next-block" onClick={()=> window.location.href='#about'}>
          <span className="arrow">О нас</span>
        </div>
        {/* <div className="welcome__shop">
         
          <button className="btn__buy">Купить</button>
        </div> */}
      </section>
      <section className="about-first path-sec" id="about">
        <div className="split">
          <div className="about bubble-right">
            <h2 className="about__text">О нас</h2>
            <p className="about__description">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
              accusantium, voluptatem tenetur tempora placeat voluptates sed
              commodi praesentium adipisci. Sit porro quidem accusamus ad
              laborum laboriosam odio dignissimos praesentium. Harum. Lorem,
              ipsum dolor sit amet consectetur adipisicing elit. Molestiae
              officiis atque nam hic et aliquam voluptatum saepe reprehenderit!
              Similique laboriosam quam cupiditate, odio fugiat velit commodi
              consectetur! Commodi, ut dolores?
            </p>
            {/* <Image
              className="about__img"
              src={socialShare}
              alt="Picture of the author"
              width="256"
              height='256'
            /> */}
            <img src="static/social_share.svg" className="about__img" alt="" />
          </div>
          <div className="way">
            <div className="ciricle ">
              {/* <Image
                className="ciricle__image"
                src={Sea}
                alt="Picture of the author"
                width="256"
                height="256"
              /> */}
              <img src="static/sea.svg" className="ciricle__image" alt="" />
            </div>
          </div>
        </div>
      </section>
      <section className="about-second path-sec">
        <div className="split">
          <div className="way">
            <div className="ciricle">
              {/* <Image
                className="ciricle__image"
                src={shops}
                alt="Picture of the author"
                width="256"
                height="256"
              /> */}
              <img src="static/shops.svg" className="ciricle__image" alt="" />
            </div>
          </div>
          <div className="about bubble-left">
            <h2 className="about__text"> Почему именно мы?</h2>
            <p className="about__description">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
              accusantium, voluptatem tenetur tempora placeat voluptates sed
              commodi praesentium adipisci. Sit porro quidem accusamus ad
              laborum laboriosam odio dignissimos praesentium. Harum. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Adipisci fugiat
              optio a quia consequuntur voluptatem consequatur quod accusamus.
              Harum quae tempora unde eos magnam accusamus, quam voluptas et
              officiis amet.
            </p>
            {/* <Image
              className="about__img"
              src={connected}
              alt="Picture of the author"
              width="256"
              height="256"
            /> */}
            <img src="static/connected.svg" className="about__img" alt="" />
          </div>
        </div>
      </section>
      <section className="delivery path-sec">
        <div className="split">
          <div className="about bubble-right">
            <h2 className="about__text">Доставка</h2>
            {/* <p className="about__description">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
              accusantium, voluptatem tenetur tempora placeat voluptates sed
              commodi praesentium adipisci. Sit porro quidem accusamus ad
              laborum laboriosam odio dignissimos praesentium. Harum. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Totam
              necessitatibus tempore veritatis, dolores eum suscipit ipsa itaque
              fugit ea maiores beatae delectus eaque laboriosam voluptatum
              cupiditate corrupti. Assumenda, rerum culpa.
            </p> */}
            {/* <Image
              className="about__img"
              src={deliveryBike}
              alt="Picture of the author"
              width="256"
              height="256"
            /> */}
            <iframe
              src="https://yandex.ru/map-widget/v1/?um=constructor%3Ace68517423ebe0f7a74e9169cdbecc57a9f2863c9049da2f71567b344c0d80e0&amp;source=constructor"
              width="497"
              height="446"
              frameBorder="0"
              style={{
                borderRadius: '25px'
              }}
            ></iframe>

            {/* <img src="static/delivery-bike.svg" className="about__img" alt="" /> */}
          </div>
          <div className="way">
            <div className="ciricle">
              {/* <Image
                className="ciricle__image"
                src={house}
                alt="Picture of the author"
                width="256"
                height="256"
              /> */}
              <img src="static/house.svg" className="ciricle__image" alt="" />
            </div>
          </div>
        </div>
      </section>
      <footer className="footer">
        <div className="wrapper">
          <div className="row space-between">
            <div className="footer-box">
              <div className="footer-title">Информация</div>
              <ul className="footer-list">
                <li className="footer-item">
                  <a href="" className="footer-link">
                    О нас
                  </a>
                </li>
                <li className="footer-item">
                  <a href="" className="footer-link">
                    Доставка и оплата
                  </a>
                </li>
                <li className="footer-item">
                  <a href="" className="footer-link">
                    Наши гарантии
                  </a>
                </li>
                <li className="footer-item">
                  <a href="" className="footer-link">
                    Как сделать заказ
                  </a>
                </li>
                <li className="footer-item">
                  <a href="" className="footer-link">
                    Контакты
                  </a>
                </li>
              </ul>
            </div>

            <div className="footer-box">
              <div className="footer-title">Время работы</div>
              <div className="footer-list">
                <div className="footer-item">
                  {/* <Image
                    className="footer-timeImage"
                    src={clock}
                    alt="Picture of the author"
                    width="256"
                    height="256"
                  /> */}
                  <img
                    src="static/clock.svg"
                    alt=""
                    className="footer-timeImage"
                  />
                  <div className="footer-workTime">с 00:00 до 25:00</div>
                </div>
              </div>
            </div>
            <div className="footer-box">
              <div className="footer-title">Наши контакты</div>
              <div className="footer-list">
                <div className="footer-item">
                  <div className="footer-phone">+7 (999) 999-99-99</div>
                </div>
                <div className="footer-item">
                  <div className="footer-email">test@mail.ru</div>
                </div>
                <div className="footer-item">
                  <div className="footer-adres">
                    г.Москва, ул. Пушкина дом Калапушкина
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="footer-bottom">
              <div className="footer-bottom-credits">FEOFISH © 2021</div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
